name: Deploy Site

on:
  push:
    branches:
      - main
# This is what will cancel the workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Continuous integration
        uses: ./.github/actions

      - name: Build
        run: npm run build

      - name: Deploying
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-southeast-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload
        run: aws s3 sync --delete ./build s3://${{ secrets.AWS_S3_BUCKET }}

      - name: Invalidate Cache CloudFront
        run: aws cloudfront create-invalidation --distribution-id "E3H4PBV3CDNGB5" --paths "/*"
